name: Publish to Ansible Galaxy

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish to Ansible Galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
